version: '3'

services:
  nodejs:
    container_name: nodejs
    ports: 
      - 3000:3000
    build:
      context: ./api
      dockerfile: ./Dockerfile
    networks:
      - mynetwork

  couchbase:
    image: couchbase:latest
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
