version: '3'

services:
  postgres:
    build:
      context: ./srcs/database
      dockerfile: Dockerfile
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: bert6
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: xcushy1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  scraper-app:
    build:
      context: ./srcs/scraper-app
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=bert6
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=postgresql
