version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork


  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - mynetwork

  nodejs-api:
    container_name: nodejs_api
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
