version: "3"

services:
  api:
    container_name: api
    ports:
      - 3000:3000
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    networks:
      - docker-network
    environment:
      - MODE_ENV=${MODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
  
  db:
    container_name:
    image: postgres:16.1 api_postgresql
    ports:
      - 6750:6750
    networks:
      - docker-network
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    networks:
      - docker-network
  
  ppgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    networks:
      - docker-network
volumes:
  grafana-storage: {}
networks:
  docker-network:
    driver: bridge
